"""empty message

Revision ID: 1854ea46fd31
Revises: d1f1b61916a0
Create Date: 2025-08-07 13:59:01.219590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1854ea46fd31'
down_revision = 'd1f1b61916a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operationslogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operationslogs', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
